### ISSUE TITLE
[Bug]: Slide build fails because of jinja templating

### ISSUE THREAD

**Issue by H-Max** [sfeir-open-source/sfeir-school-dbt#8]
### Describe the bug

The generation of slides using Github Actions fails because of Jinja code in the slides.

Example : /docs/markdown/50-jinja-and-macros/20-macros.md
Line 24

```
`/macros/formulas/turnover.sql`
```sql[]
{% macro turnover() %}
    (base_price * quantity - rebate)
{% endmacro %}

{% macro raw_turnover() %}
    (base_price * quantity)
{% endmacro %}
```

Sample build with issue : https://github.com/sfeir-open-source/sfeir-school-dbt/actions/runs/5376458886/jobs/9753637324

### Expected behavior

Do not try to apply jinja substitutions in the code blocks of slides.

**Comment by jefBinomed** [comment]
Trouvé !!! fix avec ça : https://github.com/sfeir-open-source/sfeir-school-dbt/commit/3ba5f1f98c754bc657bc50e24a1d6065a23ca995 en gros, c'était un problème de Jekyll où il fallait lui faire ignorer du code mis dans vos slides. Merci pour le bug, ça va faire un ajout à la doc ^^'. Car ça, je l'aurais jamais trouvé tout seul

**Comment by H-Max** [comment]
Oké, je vais pousser une mise à jour de la school et voir si ça compile bien, merci !

**Comment by jefBinomed** [comment]
c'est fait déjà ;)
